name: Fetch Names.json

on:
  schedule:
    - cron: "22 4 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fetch-names:
    name: Fetch names.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get names.json
        run: curl -fsSL -o data/cache/names.json https://raw.githubusercontent.com/runelite/static.runelite.net/gh-pages/cache/item/names.json
      
      - name: Push updated names.json (only if changed)
        env:
          GIT_AUTHOR_NAME: bot
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: bot
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          set -eo pipefail
          git add data/cache/names.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "automated names.json update [skip ci]"
          git push